<?php
$z[0]=Array("field","",53,81);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",83,112);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",153,181);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n               <li><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n               ",280,478);
$z[3][4]=array();
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";

?>