<?php
$z[0]=Array("litpic","",108,123);
$z[0][4]=array();
$z[1]=Array("arcurl","",161,177);
$z[1][4]=array();
$z[2]=Array("title","",179,194);
$z[2][4]=array();
$z[3]=Array("description","",219,269);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,110)";
$z[4]=Array("arcurl","",347,363);
$z[4][4]=array();
$z[5]=Array("arcurl","",434,450);
$z[5][4]=array();
$z[6]=Array("title","",452,467);
$z[6][4]=array();

?>