<?php
$z[0]=Array("senddate","\r\n\r\n            \$ntime = time();\r\n\r\n            \$oneday = 3600 * 24;\r\n\r\n            if((\$ntime - @me) < \$oneday)\r\n\r\n            @me = \"<font color='red'>(new)</font>\";\r\n\r\n            else @me = \"\";\r\n\r\n            ",0,259);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("litpic","",369,384);
$z[1][4]=array();
$z[2]=Array("arcurl","",422,438);
$z[2][4]=array();
$z[3]=Array("title","",440,455);
$z[3][4]=array();
$z[4]=Array("description","",480,530);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,110)";
$z[5]=Array("arcurl","",608,624);
$z[5][4]=array();

?>