<?php
$z[0]=Array("field","",167,195);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",197,226);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",251,272);
$z[2][4]=array();
$z[2][4]['name']="content";
$z[3]=Array("field","",592,621);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("field","",650,679);
$z[4][4]=array();
$z[4][4]['name']="typename";
$z[5]=Array("global","",744,776);
$z[5][4]=array();
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("channel"," \r\n                <div class=\"l-box\">\r\n                    <div class=\"l-icon front-icon\"></div>\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>\r\n                    <button class=\"l-button\" onclick=\"window.location.href='[field:typelink/]'\">Read More</button>\r\n                </div>\r\n            ",920,1447);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";
$z[7]=Array("arclist","\r\n            <div class=\"l-box\" id=\"box\">\r\n                <div class=\"l-icon\" style=\"background-image: url('[field:litpic/]');\"></div>\r\n                <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                <p>[field:description function='cn_substr(@me,110)'/]</p>\r\n                <button class=\"l-button\" onclick=\"window.location.href='[field:arcurl /]'\">Read More</button>\r\n                [field:global name=autoindex runphp=\"yes\"]  \r\n                if(@me%2==0)@me=\"<hr />\";  \r\n                else @me=\"\";  \r\n                [/field:global] \r\n            </div>\r\n            ",1480,2124);
$z[7][4]=array();
$z[7][4]['titlelen']="60";
$z[7][4]['row']="8";
$z[8]=Array("arclist","\r\n            <div class=\"l-box\" id=\"box\">\r\n                <div class=\"l-icon\" style=\"background-image: url('[field:litpic/]');\"></div>\r\n                <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                <p>[field:description function='cn_substr(@me,110)'/]</p>\r\n                <button class=\"l-button\" onclick=\"window.location.href='[field:arcurl /]'\">Read More</button>\r\n            </div>\r\n            ",2145,2616);
$z[8][4]=array();
$z[8][4]['titlelen']="60";
$z[8][4]['row']="8";

?>