<?php
$z[0]=Array("channel"," \r\n                <div class=\"l-box\">\r\n                    <div class=\"l-icon front-icon\"></div>\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>\r\n                    <button class=\"l-button\">Read More</button>\r\n                </div>\r\n                <a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>\r\n            ",422,991);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['noself']="yes";

?>