<?php
$z[0]=Array("litpic","",87,102);
$z[0][4]=array();
$z[1]=Array("arcurl","",140,156);
$z[1][4]=array();
$z[2]=Array("title","",158,173);
$z[2][4]=array();
$z[3]=Array("description","",198,248);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,110)";
$z[4]=Array("arcurl","",326,342);
$z[4][4]=array();
$z[5]=Array("arcurl","",413,429);
$z[5][4]=array();
$z[6]=Array("title","",431,446);
$z[6][4]=array();

?>