<div class="p-box">
                <p class="p-box-heading"><a href="[field:textlink/]">[field:textname/]</a></p>
                <div class="p-monthly">
                    <a href="[field:textlink/]">12$</a>
                    <p>Monthly</p>
                </div>
                <p class="p-b-details">Free plan available when you regisration you account</p>
                <button class="p-button" onclick="window.location.href='[field:textlink/]'">Start now</button>
            </div>