<?php
$z[0]=Array("arcurl","",394,410);
$z[0][4]=array();
$z[1]=Array("title","",412,427);
$z[1][4]=array();
$z[2]=Array("litpic","",587,602);
$z[2][4]=array();
$z[3]=Array("arcurl","",640,656);
$z[3][4]=array();
$z[4]=Array("title","",658,673);
$z[4][4]=array();
$z[5]=Array("description","",698,748);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,110)";
$z[6]=Array("arcurl","",826,842);
$z[6][4]=array();

?>