<?php
$z[0]=Array("litpic","",96,111);
$z[0][4]=array();
$z[1]=Array("arcurl","",149,165);
$z[1][4]=array();
$z[2]=Array("title","",167,182);
$z[2][4]=array();
$z[3]=Array("description","",207,257);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,110)";
$z[4]=Array("arcurl","",335,351);
$z[4][4]=array();
$z[5]=Array("global","  \r\n                if(@me%2==0)@me=\"<hr />\";  \r\n                else @me=\"\";  \r\n                ",390,544);
$z[5][4]=array();
$z[5][4]['name']="autoindex";
$z[5][4]['runphp']="yes";

?>