<?php
$z[0]=Array("field","",167,190);
$z[0][4]=array();
$z[0][4]['name']="typelink";
$z[1]=Array("field","",192,221);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel"," \r\n                <div class=\"l-box\">\r\n                    <div class=\"l-icon front-icon\"></div>\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>\r\n                    <button class=\"l-button\">Read More</button>\r\n                </div>\r\n            ",472,948);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>