<?php
$z[0]=Array("field","",167,195);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",197,226);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",251,272);
$z[2][4]=array();
$z[2][4]['name']="content";
$z[3]=Array("field","",573,602);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("field","",631,660);
$z[4][4]=array();
$z[4][4]['name']="typename";
$z[5]=Array("include","",725,764);
$z[5][4]=array();
$z[5][4]['filename']="service.html";
$z[6]=Array("channel"," \r\n                <div class=\"l-box\">\r\n                    <div class=\"l-icon front-icon\"></div>\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>\r\n                    <button class=\"l-button\" onclick=\"window.location.href='[field:typelink/]'\">Read More</button>\r\n                </div>\r\n            ",891,1418);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['noself']="yes";
$z[7]=Array("include","",1456,1495);
$z[7][4]=array();
$z[7][4]['filename']="service.html";
$z[8]=Array("arclist","\r\n            <div class=\"l-box\" id=\"box\">\r\n                <div class=\"l-icon\" style=\"background-image: url('[field:litpic/]');\"></div>\r\n                <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                <p>[field:description function='cn_substr(@me,110)'/]</p>\r\n                <button class=\"l-button\" onclick=\"window.location.href='[field:arcurl /]'\">Read More</button>\r\n            </div>\r\n            ",1518,1989);
$z[8][4]=array();
$z[8][4]['titlelen']="60";
$z[8][4]['row']="8";

?>