<?php
$z[0]=Array("field","",167,196);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",198,227);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel"," \r\n                <div class=\"l-box\">\r\n                    <div class=\"l-icon front-icon\"></div>\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>\r\n                    <button class=\"l-button\" onclick=\"window.location.href='[field:typelink/]'\">Read More</button>\r\n                </div>\r\n            ",483,1010);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("channelartlist","\r\n            <div class=\"l-box\">\r\n                <div class=\"l-icon front-icon\"></div>\r\n                <a href=\"{dede:field name='typeurl' ",1047,1231);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['row']="8";
$z[4]=Array("field","",1233,1262);
$z[4][4]=array();
$z[4][4]['name']="typename";
$z[5]=Array("field","",1488,1519);
$z[5][4]=array();
$z[5][4]['name']="\\'typeurl\\'";

?>