<?php
$z[0]=Array("field","",80,101);
$z[0][4]=array();
$z[0][4]['name']="litpic";
$z[1]=Array("field","",198,226);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",228,257);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",282,303);
$z[3][4]=array();
$z[3][4]['name']="content";
$z[4]=Array("channel"," \r\n                <div class=\"l-box\">\r\n                    <div class=\"l-icon front-icon\"></div>\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>\r\n                    <button class=\"l-button\" onclick=\"window.location.href='[field:typelink/]'\">Read More</button>\r\n                </div>\r\n            ",501,1028);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";
$z[5]=Array("arclist","\r\n            <div class=\"l-box\">\r\n                <div class=\"l-icon front-icon\" id=\"icon\"></div>\r\n                <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                <p>[field:description function='cn_substr(@me,110)'/]</p>\r\n                <button class=\"l-button\" onclick=\"window.location.href='[field:arcurl /]'\">Read More</button>\r\n            </div>\r\n            <!-- ·<a href=\"[field:arcurl /]\">[field:title /]</a><br> -->\r\n            ",1065,1573);
$z[5][4]=array();
$z[5][4]['titlelen']="60";
$z[5][4]['row']="8";

?>