<?php
$z[0]=Array("field","",167,195);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",197,226);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",251,272);
$z[2][4]=array();
$z[2][4]['name']="content";
$z[3]=Array("channel"," \r\n                <div class=\"l-box\">\r\n                    <div class=\"l-icon front-icon\"></div>\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>\r\n                    <button class=\"l-button\" onclick=\"window.location.href='[field:typelink/]'\">Read More</button>\r\n                </div>\r\n            ",470,997);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[4]=Array("arclist","\r\n            <div class=\"l-box\" id=\"box\">\r\n                <script>\r\n                    if(\"{dede:field name='typename'/}\" == \"service\") {\r\n                        document.getElementById(\"box\").innerHTML = \"<div>xxxxxxxx</div>\"\r\n                        // document.getElementById(\"box\").innerHTML = '<div class=\"l-icon\"></div><a href=\"[field:arcurl /]\">[field:title /]</a>';\r\n                    }\r\n               </script>\r\n                <!-- <div class=\"l-icon\" style=\"background-image: url('[field:litpic/]');\"></div>\r\n                <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                <p>[field:description function='cn_substr(@me,110)'/]</p>\r\n                <button class=\"l-button\" onclick=\"window.location.href='[field:arcurl /]'\">Read More</button> -->\r\n            </div>\r\n            <!-- ·<a href=\"[field:arcurl /]\">[field:title /]</a><br> -->\r\n            ",1034,1973);
$z[4][4]=array();
$z[4][4]['titlelen']="60";
$z[4][4]['row']="8";

?>