<?php
$z[0]=Array("arcurl","",460,476);
$z[0][4]=array();
$z[1]=Array("title","",478,493);
$z[1][4]=array();
$z[2]=Array("litpic","",653,668);
$z[2][4]=array();
$z[3]=Array("arcurl","",706,722);
$z[3][4]=array();
$z[4]=Array("title","",724,739);
$z[4][4]=array();
$z[5]=Array("description","",764,814);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,110)";
$z[6]=Array("arcurl","",892,908);
$z[6][4]=array();

?>