<?php
$z[0]=Array("global","",268,300);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",352,384);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",469,501);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",595,627);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("include","",687,723);
$z[4][4]=array();
$z[4][4]['filename']="head.html";
$z[5]=Array("field","",968,991);
$z[5][4]=array();
$z[5][4]['name']="typename";
$z[6]=Array("sql"," \r\n            <p>[field:content  function='cn_substr(html2text(@me),524)'/]</p>\r\n            ",1011,1184);
$z[6][4]=array();
$z[6][4]['sql']="Select content from dede_arctype where id=~typeid~";
$z[7]=Array("field","",1457,1475);
$z[7][4]=array();
$z[7][4]['name']="body";
$z[8]=Array("include","",1694,1732);
$z[8][4]=array();
$z[8][4]['filename']="footer.html";

?>