<?php
$z[0]=Array("litpic","",119,134);
$z[0][4]=array();
$z[1]=Array("arcurl","",172,188);
$z[1][4]=array();
$z[2]=Array("title","",190,205);
$z[2][4]=array();
$z[3]=Array("description","",230,280);
$z[3][4]=array();
$z[3][4]['function']="cn_substr(@me,110)";
$z[4]=Array("arcurl","",358,374);
$z[4][4]=array();
$z[5]=Array("arcurl","",449,465);
$z[5][4]=array();
$z[6]=Array("title","",467,482);
$z[6][4]=array();

?>