<?php
$z[0]=Array("field","",167,196);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",198,227);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel"," \r\n                <div class=\"l-box\">\r\n                    <div class=\"l-icon front-icon\"></div>\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>\r\n                    <button class=\"l-button\" onclick=\"window.location.href='[field:typelink/]'\">Read More</button>\r\n                </div>\r\n            ",483,1010);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("arclist","\r\n            <div class=\"l-box\">\r\n                <div class=\"l-icon front-icon\"></div>\r\n                <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n                <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>\r\n                <button class=\"l-button\" onclick=\"window.location.href='[field:arcurl /]'\">Read More</button>\r\n            </div>\r\n            <!-- ·<a href=\"[field:arcurl /]\">[field:title /]</a><br> -->\r\n            ",1047,1604);
$z[3][4]=array();
$z[3][4]['row']="8";

?>