<div class="l-box">
                {dede:field.image/}
                <div class="l-icon front-icon" id="icon"></div>
                <a href="[field:arcurl /]">[field:title /]</a>
                <p>[field:description function='cn_substr(@me,110)'/]</p>
                <button class="l-button" onclick="window.location.href='[field:arcurl /]'">Read More</button>
            </div>
            <!-- ·<a href="[field:arcurl /]">[field:title /]</a><br> -->