<div class="l-box">
                <div class="l-icon front-icon"></div>
                <a href="[field:arcurl /]">[field:title /]</a>
                <p>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</p>
                <button class="l-button" onclick="window.location.href='[field:arcurl /]'">Read More</button>
            </div>
            <!-- ·<a href="[field:arcurl /]">[field:title /]</a><br> -->