
    <section class="list-article">
        <!-- service-heading start -->
        <div class="l-heading">
            <!-- <p>Services</p> -->
            <p>
                [field:typename/]
            </p>
            <p>Our Services,Trems and Conditions</p>
        </div>
        <!-- service-heading end -->
        <!-- service-box-container start -->
        <div class="l-box-container">
            <!-- s-box-1 start -->
                <!-- <div class="l-box">
                    <div class="l-icon front-icon"></div>
                    <a href="[field:typelink/]">[field:typename/]</a>
                    <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>
                    <button class="l-button">Read More</button>
                </div>
                <a href="[field:typelink/]" title="[field:typename/]">[field:typename/]</a> -->
            
            <!-- <div class="l-box">
                <div class="l-icon front-icon"></div>
                <a href="#">Front End Develop</a>
                <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>
                <button class="l-button">Read More</button>
            </div> -->
            <!-- s-box-1 end -->
            <!-- s-box-1 start -->
            <!-- <div class="l-box">
                <div class="l-icon back-icon"></div>
                <a href="#">Back End</a>
                <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>
                <button class="l-button">Read More</button>
            </div> -->
            <!-- s-box-1 end -->
            <!-- s-box-1 start -->
            <!-- <div class="l-box">
                <div class="l-icon seo-icon"></div>
                <a href="#">SEO/Security</a>
                <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>
                <button class="l-button">Read More</button>
            </div> -->
            <!-- s-box-1 end -->
            <!-- s-box-1 start -->
            <!-- <div class="l-box">
                <div class="l-icon gui-icon"></div>
                <a href="#">GUI</a>
                <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>
                <button class="l-button">Read More</button>
            </div> -->
            <!-- s-box-1 end -->
        </div>
        