<?php
$z[0]=Array("global","",73,98);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",328,353);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n        <a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a>\r\n        ",389,625);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[3]=Array("global","",652,677);
$z[3][4]=array();
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n            <a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a>\r\n            ",702,897);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<a href='~typelink~' ~rel~>~typename~</a>";

?>