<?php
$z[0]=Array("global","",268,300);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",408,440);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",529,561);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",655,687);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",737,769);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",827,863);
$z[5][4]=array();
$z[5][4]['filename']="head.html";
$z[6]=Array("type","\r\n                    [field:typename/]\r\n                ",1073,1153);
$z[6][4]=array();
$z[7]=Array("channel","\r\n                <div class=\"l-box\">\r\n                    <div class=\"l-icon front-icon\"></div>\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <p>This website is best for your website make plan and this website pro10 /10 website services that other website not provide.</p>\r\n                    <button class=\"l-button\">Read More</button>\r\n                </div>\r\n                <a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>\r\n            ",1419,1974);
$z[7][4]=array();
$z[7][4]['type']="son";
$z[8]=Array("include","",3832,3870);
$z[8][4]=array();
$z[8][4]['filename']="footer.html";
$z[9]=Array("global","",3946,3978);
$z[9][4]=array();
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",4031,4063);
$z[10][4]=array();
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("field","",4118,4147);
$z[11][4]=array();
$z[11][4]['name']="typename";

?>