<?php
$z[0]=Array("arclist","\r\n[field:title /]\r\n<div class=\"l-box\" id=\"box\">\r\n    <div class=\"l-icon\" style=\"background-image: url('[field:litpic/]');\"></div>\r\n    <a href=\"[field:arcurl /]\">[field:title /]</a>\r\n    <p>[field:description function='cn_substr(@me,110)'/]</p>\r\n    <button class=\"l-button\" onclick=\"window.location.href='[field:arcurl /]'\">Read More</button>\r\n</div>\r\n",0,404);
$z[0][4]=array();
$z[0][4]['titlelen']="60";
$z[0][4]['row']="8";

?>