<?php  exit();
/*
Page: /dede/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=15&pageno=1&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''#@_arctype' where id=3' at line 1 <br />Error sql: <font color='red'>select content from '#@_arctype' where id=3</font>
Time2021-06-21 15:47:37
*/
?>
<?php  exit();
/*
Page: /dede/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=15&pageno=1&isremote=0&serviterm=
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''#@_arctype' where id=16' at line 1 <br />Error sql: <font color='red'>select content from '#@_arctype' where id=16</font>
Time2021-06-21 15:48:57
*/
?>
<?php  exit();
/*
Page: /dede/sys_sql_query.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''#@_arctype' where id=16'' at line 1 <br />Error sql: <font color='red'>select content from '#@_arctype' where id=16'</font>
Time2021-06-21 16:02:54
*/
?>
<?php  exit();
/*
Page: /dede/sys_sql_query.php
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''' at line 1 <br />Error sql: <font color='red'>select content from `#@_arctype` where id=16'</font>
Time2021-06-21 16:03:05
*/
?>
<?php  exit();
/*
Page: /dede/sys_sql_query.php
Error: Table 'dedecmsv57utf8sp2.#@_arctype' doesn't exist <br />Error sql: <font color='red'>select content from `#@_arctype` where id=16</font>
Time2021-06-21 16:03:45
*/
?>
<?php  exit();
/*
Page: /dede/sys_sql_query.php
Error: Table 'dedecmsv57utf8sp2.#@_arctype' doesn't exist <br />Error sql: <font color='red'>select content from `#@_arctype` where id=16</font>
Time2021-06-21 16:03:47
*/
?>
<?php  exit();
/*
Page: /dede/sys_sql_query.php
Error: Table 'dedecmsv57utf8sp2.#@_arctype' doesn't exist <br />Error sql: <font color='red'>select content from `#@_arctype` where id=16</font>
Time2021-06-21 16:04:02
*/
?>
<?php  exit();
/*
Page: /dede/sys_sql_query.php
Error: Table 'dedecmsv57utf8sp2.#@_arctype' doesn't exist <br />Error sql: <font color='red'>select content from `#@_arctype` where id=16</font>
Time2021-06-21 16:04:05
*/
?>
